### ISSUE TITLE
`image` URLs are incorrect in People data

### ISSUE THREAD

**Issue by gvn** [mozilla/network-api#145]
To repro:

1. Go to: https://network-api.mofoprod.net/api/people/?format=json&featured=True&page=1
2. Try to load any of the `image` URLs
3. Get error message

Expected:

Image asset resolves.

**Comment by cadecairos** [comment]
I suspect this is related to: #144

When @Pomax and I implemented filebrowser_s3, we found that we needed to remove the `AWS_STORAGE_LOCATION` variable to ensure that the file browser would work properly. However it appears that boto3 uses this internally when resolving the stored paths to images for people, features, and news.

We're going to have to figure out a way to either:

1. Have filebrowser_s3 work properly with `AWS_STORAGE_LOCATION` set (might not even be possible?)
2. Store the bucket name in the paths we create when uploading images (outside of filebrowser_safe), and update all existing paths (probably the simplest option)
3. Have the forms for people/news/features use filebrowser_safe for image uploads and re-upload all the images (ideal solution, most work fixing breakage)

**Comment by gvn** [comment]
Should we roll back prod to unbreak the front end while we work on a solution?

**Comment by Pomax** [comment]
Technically the filebrowser_s3 code no longer depends directly on `AWS_STORAGE_ROOT` directly, although it does send URLs through the boto3... we can see what happens when we set both it and `FILEBROWSER_DIRECTORY` to `network`.

**Comment by Pomax** [comment]
@gvn if prod was updated then that might not be a bad idea.

**Comment by Pomax** [comment]
@cadecairos looking at https://django-storages.readthedocs.io/en/latest/backends/amazon-S3.html, which are the s3boto3 docs, I don't see any mention of AWS_STORAGE_ROOT anywhere... so are you sure boto3 relies on it?

**Comment by Pomax** [comment]
Looking at staging, I see:

- https://network-api.mofostaging.net/api/people/?format=json&featured=True&page=1 yields a response with images `https://assets.mofostaging.net/images/people/.......png`
- looking in the database, that image field is encoded as `images/people/.......png`

Other than the `people/models.py` image field, which is a `FileField` with an `upload` function that literally generates URLs on `images/...` I do not see anything else that might be involved in creating the paths for these images, and so from what I can tell, it might be worth making sure the upload path is correct by tapping into either AWS_STORAGE_ROOT or FILEBROWSER_DIRECTORY (probably the first?) so that images are *uploaded* to the right spot, and then manually update the db so that all paths start with `network/...`

Thoughts @cadecairos ?

**Comment by Pomax** [comment]
fixed, and the working filebrowser_s3 has been published as v1.0.0
