### ISSUE TITLE
Clarify people "affiliations"

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-api#176]
At the bottom of the "people" model admin, we've got a section for "affiliations".
<img width="1144" alt="image" src="https://cloud.githubusercontent.com/assets/1682681/25583207/cf3bac14-2e5e-11e7-8995-a71f5be20b49.png">

What useful text can we put there to make its purpose clearer?

**Comment by taisdesouzalessa** [comment]
That is a very good point, @alanmoo. I am not sure I have the answer for this one.

My first thought was to label it "role" or "job title". However it doesn't make sense for somebody like Bruno because he is also a PhD student:
<img width="471" alt="image" src="https://cloud.githubusercontent.com/assets/22157921/25598254/c6914efa-2e88-11e7-8d42-1ffb6133108e.png">

Another example that stood out to me (we don't have his role in this page - instead we have his relationship with Mozilla):
<img width="548" alt="image" src="https://cloud.githubusercontent.com/assets/22157921/25598336/444e8e70-2e89-11e7-832b-23cf5ac09b4a.png">

Maybe @KevZawacki has some ideas of labels that can encompass the variety of things we can have in this field?

**Comment by KevZawacki** [comment]
@taisdesouzalessa "Affiliations" is a good catchall. Maybe we put some examples in parenthesis, to be more clear? So it would look like:

Affiliations (e.g. companies, nonprofits, universities, projects and other organizations you're actively involved with)

**Comment by alanmoo** [comment]
Sounds great @KevZawacki, I can add that in as help text.
