### ISSUE TITLE
Prevent opening of "Opportunity" top level page

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-api#208]
Related to #207 and #192, we should make it so that the top level page "Opportunities" isn't clickable, as it's just a placeholder.

![image](https://cloud.githubusercontent.com/assets/1682681/26176851/919ab2dc-3b25-11e7-9942-b0501ebc44aa.png)

**Comment by Pomax** [comment]
I've updated it to look like this:

![image](https://cloud.githubusercontent.com/assets/177243/26225899/4d26af7a-3bde-11e7-8497-c37fbb0a295b.png)

This makes the top level page editable but only to superusers (regular users see an inert string), with the "add a new page" tied to the heading. Children can be reordered but *cannot* be nested under each other (using `sortable` rather than `nestedSortable`). I've also turned off the ridiculous automatic-tree-collapse that is applied in the js code for this page

Also the amount of `float` in mezzanine is amazing and horrible at the same time >_>
