### ISSUE TITLE
People Publish Filter is Off by 21 Hours

### ISSUE THREAD

**Issue by cadecairos** [mozilla/network-api#219]
During some debugging today, we noticed that in order for a person record to show up in the api view, the publish_after datetime needs to be at least 21 hours in the past to the current time in UTC (i.e if it's `2017-6-7 16:00:00 UTC`, publish_after needs to be less than `2017-6-6 21:00:00 UTC` in order to be visible in the api view)

There may be more in play here than we know - TZ of the browser editing the field, TZ of the server, etc.

**Comment by alanmoo** [comment]
Now that editors can publish without dev involvement, this is going to become a more glaring issue.

**Comment by Pomax** [comment]
Do we have any steps to reproduce this locally?

**Comment by alanmoo** [comment]
Nope, it seems to work fine locally, which leads me to believe it's something around server time zones and the time zone that gets applied when saving the "Publish after" field.

**Comment by Pomax** [comment]
yeah, I tried to publish a `People` instance and playing around with its `publish_after` set to various times, but it seemed to do what I would have expected it to do rather than introducing a 21 hour differential.

**Comment by alanmoo** [comment]
Are you talking about in a local environment?

On network-dev.mofostaging.net, I created a new person and the default time was 
<img width="606" alt="screen shot 2017-06-22 at 10 19 36 am" src="https://user-images.githubusercontent.com/1682681/27438784-51c70892-5734-11e7-92df-cafe8915aa4c.png">
(at 10:17AM Eastern Daylight Time). Clicking "Publish" would not show the new person at network-dev.mofostaging.net/api/people, but clicking the "now" button updates the field to 10:17:xx and saving does result in the entry appearing on the API. So perhaps the issue is more of a disconnect between the admin and the view with how they handle time zones? Perhaps the admin simply needs the initial value to be in local time? I'm not sure where the 21 hours comes in though.

**Comment by Pomax** [comment]
I actually then set `publish after` to a few days into the future but it kept showing up. Could be I was hitting cache.

**Comment by alanmoo** [comment]
Caching was turned off Tuesday night- have you checked since then? That might have been some of the problem.

**Comment by Pomax** [comment]
Alright so it looks like postgres is storing the correct time *and* it "knows" what the correct time is, so the error is not in how the database record is stored, and purely on how the database record gets interpreted.

```
 f        |                                                         |                                      |         | 2017-06-22 14:16:41+00        |    32 |
 40 | Pomax                       | Pomax                                             | Pomax                       | images/people/pomax_1498167212.jpg                       |                                                                                                                                                                                                                                                                                                |                                                                |                                                                                                                                                                                    | f        |                                                         |                                      |         | 2017-06-22 21:32:57+00        |    34 |
(34 rows)
```
With postgres's knowledge of time when the record's not showing up in the API response:
```
dcr30no5l97haa=> select current_timestamp;
              now
-------------------------------
 2017-06-22 21:52:01.378582+00
(1 row)
```

**Comment by Pomax** [comment]
I added the following code to the People models.py to see what Django thought about the local time:
```
        if settings.DEBUG is True:
            tz = timezone.get_current_timezone()
            print("django thinks the current timezone is:", tz)
            print("django thinks 'now' is:", now)
            # last = self.last()
            # print(
            #     "last People entry publish_after is set to:",
            #     last.publish_after
            # )
```
And this shows Django itself getting the time "right":
```
2017-06-22T22:38:08.939875+00:00 app[web.1]: django thinks the current timezone is: UTC
2017-06-22T22:38:08.939886+00:00 app[web.1]: django thinks 'now' is: 2017-06-22 22:38:08.939755+00:00
2017-06-22T22:38:08.941633+00:00 app[web.1]: django thinks the current timezone is: UTC
2017-06-22T22:38:08.941671+00:00 app[web.1]: django thinks 'now' is: 2017-06-22 22:38:08.941572+00:00
```

Those timestamps matched the actual UTC time at the moment of logging.

**Comment by cadecairos** [comment]
perhaps the time issue is in the comparison done in the sql query?

**Comment by Pomax** [comment]
I tried to see if explicitly converting to naive format made the check succeed, but no such luck.

**Comment by Pomax** [comment]
Tried to make a user without touching the "publish_after" autosuggestion. Saving and reloading the `/api/people/` end point did nothing. Restarting the dyno, however, then showed the new person just fine.

Something is interfering with DRF responses something fierce...

**Comment by arush0311** [comment]
I think this is also a bug in grapelli. since the time after cliking `now` is not in UTC timezone

**Comment by Pomax** [comment]
It turns out that querysets come with their own caching, and so we changed https://github.com/mozilla/network-api/blob/master/app/networkapi/people/views.py#L12 to ensure the queryset is not cached at the time of class-instance creation. 

This solves the problem of "I don't see any results until X hours later" (which could be cut short by restarting the dyno, which was a clue that it wasn't actually timezones interfering) but requires further code audits to see where else this might be happening.

#232 has been filed to tackle this investigation.
