### ISSUE TITLE
Build model for News Publications and Icons

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-api#224]
Thoughts from CMS training:

Currently users have to upload a glyph for news articles, which means they're highly unlikely to have something that fits. Can we use the media library for glyphs instead, so that if one exists for a publication already, we can point to it? Or better yet, should we create a "publication" model so that we can attach the glyphs directly to the publication instead of the article?

cc @hannahkane @xmatthewx @Pomax

**Comment by Pomax** [comment]
question: I have worked with fonts and languages for years, the only "glyph" I know is "any written symbol or compositional part thereof"... so with that framing I have no idea what the question is here =D

**Comment by alanmoo** [comment]
Touché. Let's try "news source icon"?

<img width="519" alt="screen shot 2017-06-16 at 1 51 53 pm" src="https://user-images.githubusercontent.com/1682681/27238501-2bc39b9e-529b-11e7-8ee4-25f508005d92.png">

<img width="1143" alt="image" src="https://user-images.githubusercontent.com/1682681/27238527-3fee0e2e-529b-11e7-9429-86ba3ed4ce4f.png">

**Comment by Pomax** [comment]
Hopefully to aid getting the terminology right, we're talking about the official brand logos for these sources, right? Just in line-height sized pictures? If so, then "source logo" or "brand logo" seems the correct term here.

**Comment by hannahkane** [comment]
+1 to building out a publication model, so we can change all icons associated with a source if we need to, and so that the person adding a news item doesn't have to think about the logo/icon at all in many cases

If we're attaching this to a publication model, we can just say "icon" or "logo." (I tend to prefer icon, since I can imagine in some cases it might not be a logo.)

If we decide not to build out a publication model, and we want to keep this on the news article form, we might use the term "outlet" since that's how we describe the source elsewhere in the form. So, "Outlet icon"? (I think I'd actually prefer to use "Source icon" and change "Outlet" to "Source" if possible.)

**Comment by xmatthewx** [comment]
does this fit in the mezzanine epic?

**Comment by alanmoo** [comment]
Let's go with the publication model.

Model name: Publication
Data:
* Name (string)
* Icon (image)

News model gets a new property called `publication` which is a foreignKey to an instance of `Publication`. Whenever a user requests a news article, they'll see the same `outlet` name and `glyph`, but it'll be from from the Publication model instead of the one previously stored on it.

Migrate the existing `outlet` and `glyph` properties from each news article into a new `Publication` item. If there's a duplicate name, reference the existing item instead (though if this ends up being difficult we can handle it manually later on without too much trouble as the data set is still manageable)

**Comment by alanmoo** [comment]
Scratch that. @arush0311 brought up a great point in chat- let's just upload a bunch of the glyphs to the media library and change the `glyph` property in the admin to allow editors to select one from the media library. Ideally we could force the admin to only allow picking from a single directory in the media library.
