### ISSUE TITLE
People need fields for twitter/linkedin profiles

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-api#43]
Text field for username on twitter. URL for linkedin?

**Comment by gideonthomas** [comment]
Isn't that what "Links" is @alanmoo? We can make this a bit clearer via the admin

**Comment by hannahkane** [comment]
FWIW, that would actually make more sense to me. Nearly everyone has twitter links, but very few have the "Other links" field completed in the spreadsheet.

**Comment by hannahkane** [comment]
But will the Twitter / LinkedIn links be show via an icon, or will the entire link be displayed?

**Comment by gideonthomas** [comment]
Depends on how much we want to lock it down to those two choices. We could do something like:

Twitter Handle:         _________
LinkedIn Username: __________
Other Links: <same ui that it currently uses for Links>

Or we could require them to input the entire url:
Twitter:        __________
LinkedIn:     ___________
Other Links: <same ui that it currently uses for Links>

We could show the icons (but that would involve me editing the html which might take some time/research) but I would refrain from it for now due to time constraints.
