### ISSUE TITLE
Create migration plan for network-api

### ISSUE THREAD

**Issue by Pomax** [mozilla/network-api#60]
two options here:
- network-api becomes Mezzanine
- django network-api and Mezzanine in some kind of coexistence with synergetic data sharing

**Comment by gideonthomas** [comment]
Closing since we've decided that we will maintain a pseudo-Mezzanine app for network api where Mezzanine lives on top of the current Django project providing its user interface and fields such as publish date, expiry, etc. but will only be responsible to generating and managing the opportunities pages while relying on stock drf to serve the rest of the models with the pages for them being hosted by the current frontend.
