### ISSUE TITLE
Ensure deploys happen on user input for content for: People, News, Features

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/network-api#68]
On a post-save hook in Mezzanine, trigger Jenkins to build and deploy a fresh site based on the cached (last committed) code and the new REST data.

**Comment by simonwex** [comment]
We should explore doing this automatically on change rather than as a UI element.

**Comment by cadecairos** [comment]
Instead of a deploy button, lets add an app that handles deployment using post-save hooks on the news, feature and person models.

We're going to want to "debounce" deployments, so that many changes to records result in fewer (preferably just one) deploys. Additionally, we want to throttle deployments so that they don't start piling up in Jenkins. Maybe one deploy per fifteen minute period?

 We might be able to use decorators that throttle and debounce the function that will trigger the build.

cc/ @simonwex @Pomax

**Comment by Pomax** [comment]
How would it know to back off? We don't have automated stage testing as far as I'm aware.

**Comment by cadecairos** [comment]
I think I might want to trigger this on post_delete signals too.

**Comment by cadecairos** [comment]
This is now done, and landed on production.
